/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMindmapsRouteImport } from './routes/_authenticated/mindmaps'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedGapsRouteImport } from './routes/_authenticated/gaps'
import { Route as AuthenticatedFormulasRouteImport } from './routes/_authenticated/formulas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMaterialsIdRouteImport } from './routes/_authenticated/materials.$id'
import { Route as AuthenticatedQuizzesIdTakeRouteImport } from './routes/_authenticated/quizzes.$id.take'
import { Route as AuthenticatedQuizzesIdResultsRouteImport } from './routes/_authenticated/quizzes.$id.results'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMindmapsRoute = AuthenticatedMindmapsRouteImport.update({
  id: '/mindmaps',
  path: '/mindmaps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGapsRoute = AuthenticatedGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormulasRoute = AuthenticatedFormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsIdRoute =
  AuthenticatedMaterialsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMaterialsRoute,
  } as any)
const AuthenticatedQuizzesIdTakeRoute =
  AuthenticatedQuizzesIdTakeRouteImport.update({
    id: '/$id/take',
    path: '/$id/take',
    getParentRoute: () => AuthenticatedQuizzesRoute,
  } as any)
const AuthenticatedQuizzesIdResultsRoute =
  AuthenticatedQuizzesIdResultsRouteImport.update({
    id: '/$id/results',
    path: '/$id/results',
    getParentRoute: () => AuthenticatedQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/formulas': typeof AuthenticatedFormulasRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/mindmaps': typeof AuthenticatedMindmapsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/review': typeof AuthenticatedReviewRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/quizzes/$id/results': typeof AuthenticatedQuizzesIdResultsRoute
  '/quizzes/$id/take': typeof AuthenticatedQuizzesIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/formulas': typeof AuthenticatedFormulasRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/mindmaps': typeof AuthenticatedMindmapsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/review': typeof AuthenticatedReviewRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/quizzes/$id/results': typeof AuthenticatedQuizzesIdResultsRoute
  '/quizzes/$id/take': typeof AuthenticatedQuizzesIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/formulas': typeof AuthenticatedFormulasRoute
  '/_authenticated/gaps': typeof AuthenticatedGapsRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/_authenticated/mindmaps': typeof AuthenticatedMindmapsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRouteWithChildren
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/_authenticated/quizzes/$id/results': typeof AuthenticatedQuizzesIdResultsRoute
  '/_authenticated/quizzes/$id/take': typeof AuthenticatedQuizzesIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/formulas'
    | '/gaps'
    | '/materials'
    | '/mindmaps'
    | '/notes'
    | '/progress'
    | '/quizzes'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/tutor'
    | '/api/chat'
    | '/materials/$id'
    | '/quizzes/$id/results'
    | '/quizzes/$id/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/formulas'
    | '/gaps'
    | '/materials'
    | '/mindmaps'
    | '/notes'
    | '/progress'
    | '/quizzes'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/tutor'
    | '/api/chat'
    | '/materials/$id'
    | '/quizzes/$id/results'
    | '/quizzes/$id/take'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/formulas'
    | '/_authenticated/gaps'
    | '/_authenticated/materials'
    | '/_authenticated/mindmaps'
    | '/_authenticated/notes'
    | '/_authenticated/progress'
    | '/_authenticated/quizzes'
    | '/_authenticated/review'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/tutor'
    | '/api/chat'
    | '/_authenticated/materials/$id'
    | '/_authenticated/quizzes/$id/results'
    | '/_authenticated/quizzes/$id/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mindmaps': {
      id: '/_authenticated/mindmaps'
      path: '/mindmaps'
      fullPath: '/mindmaps'
      preLoaderRoute: typeof AuthenticatedMindmapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gaps': {
      id: '/_authenticated/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AuthenticatedGapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formulas': {
      id: '/_authenticated/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof AuthenticatedFormulasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials/$id': {
      id: '/_authenticated/materials/$id'
      path: '/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AuthenticatedMaterialsIdRouteImport
      parentRoute: typeof AuthenticatedMaterialsRoute
    }
    '/_authenticated/quizzes/$id/take': {
      id: '/_authenticated/quizzes/$id/take'
      path: '/$id/take'
      fullPath: '/quizzes/$id/take'
      preLoaderRoute: typeof AuthenticatedQuizzesIdTakeRouteImport
      parentRoute: typeof AuthenticatedQuizzesRoute
    }
    '/_authenticated/quizzes/$id/results': {
      id: '/_authenticated/quizzes/$id/results'
      path: '/$id/results'
      fullPath: '/quizzes/$id/results'
      preLoaderRoute: typeof AuthenticatedQuizzesIdResultsRouteImport
      parentRoute: typeof AuthenticatedQuizzesRoute
    }
  }
}

interface AuthenticatedMaterialsRouteChildren {
  AuthenticatedMaterialsIdRoute: typeof AuthenticatedMaterialsIdRoute
}

const AuthenticatedMaterialsRouteChildren: AuthenticatedMaterialsRouteChildren =
  {
    AuthenticatedMaterialsIdRoute: AuthenticatedMaterialsIdRoute,
  }

const AuthenticatedMaterialsRouteWithChildren =
  AuthenticatedMaterialsRoute._addFileChildren(
    AuthenticatedMaterialsRouteChildren,
  )

interface AuthenticatedQuizzesRouteChildren {
  AuthenticatedQuizzesIdResultsRoute: typeof AuthenticatedQuizzesIdResultsRoute
  AuthenticatedQuizzesIdTakeRoute: typeof AuthenticatedQuizzesIdTakeRoute
}

const AuthenticatedQuizzesRouteChildren: AuthenticatedQuizzesRouteChildren = {
  AuthenticatedQuizzesIdResultsRoute: AuthenticatedQuizzesIdResultsRoute,
  AuthenticatedQuizzesIdTakeRoute: AuthenticatedQuizzesIdTakeRoute,
}

const AuthenticatedQuizzesRouteWithChildren =
  AuthenticatedQuizzesRoute._addFileChildren(AuthenticatedQuizzesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormulasRoute: typeof AuthenticatedFormulasRoute
  AuthenticatedGapsRoute: typeof AuthenticatedGapsRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRouteWithChildren
  AuthenticatedMindmapsRoute: typeof AuthenticatedMindmapsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRouteWithChildren
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormulasRoute: AuthenticatedFormulasRoute,
  AuthenticatedGapsRoute: AuthenticatedGapsRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRouteWithChildren,
  AuthenticatedMindmapsRoute: AuthenticatedMindmapsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRouteWithChildren,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
