// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// The supabase import is dynamic on purpose. start.ts is the app entry, so a
// static import here put the whole Supabase SDK — 207 kB — into the eager client
// graph of every page, including the logged-out landing page, which never calls
// a server function. Loading it on first use costs nothing: by the time a
// serverFn runs we are already awaiting the network.
//
// NOTE: this file carries a "do not edit, automatically generated" banner. If a
// generator ever rewrites it, this dynamic import is the thing to restore.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { supabase } = await import('./client')
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
